name: Build Pull Request

on:
  pull_request:
    paths:
      - '.github/workflows/**/*'
      - '.eslintrc.json'
      - 'gulpfile.ts'
      - 'tsconfig.json'
      - 'bin/**/*'
      - 'config/**/*'
      - 'src/**/*'
      - 'templates/**/*'
      - 'test/**/*'

jobs:
  build:
    name: Build and Test
    uses: tyler-technologies/forge-automation-shared/.github/workflows/wf-build-and-test.yml@v0.10.0
    with:
      TESTS_ENABLED: true
    secrets:
      ARTIFACTORY_TOKEN: ${{ secrets.FORGE_ARTIFACTORY_TOKEN }}
      ARTIFACTORY_USERNAME: ${{ secrets.FORGE_ARTIFACTORY_USERNAME }}
      ARTIFACTORY_REGISTRY: ${{ secrets.FORGE_ARTIFACTORY_NPM_REGISTRY }}
